storePassword=23121985
keyPassword=23121985
keyAlias=edupro
storeFile= ../app/edupro.jks
#storeFile=<location of the key store file, such as /Users/<user name>/upload-keystore.jks>



#8B:C6:92:7B:4F:1A:84:50:48:EB:B9:B9:EE:DB:E5:72:A0:99:E2:3C

#00:AC:86:BA:1A:3A:30:88:C9:4F:CA:73:27:61:20:34:10:66:4C:D8:58:F4:9A:B6:23:15:F5:92:DB:75:2F:AA